name: CI

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node v14
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: yarn install
        run: yarn install
      - name: yarn test
        run: yarn test
      - name: yarn build
        run: yarn build
      - name: codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          name: codecov # optional
          flags: unittest
          fail_ci_if_error: true # optional (default = false)
          #directory: ./coverage/reports/
          #files: ./coverage1.xml,./coverage2.xml
          verbose: true # optional (default = false)
